// Advanced Equipment & MHE Exports
export {
  MHEEngine,
  getMHEEngine,
  setMHEEngine,
  type RecordTelematicsInput,
  type CreateGeofenceInput,
  type RegisterCertificationInput,
  type RecordTrainingInput,
  type ReportIncidentInput,
  type SubmitSafetyCheckInput,
  type RegisterChargingDockInput,
  type StartChargingInput,
  type RecordBatterySwapInput,
  type CreateWorkOrderInput as CreateMHEWorkOrderInput,
  type RegisterLifecycleInput,
} from './mhe-engine';

// Re-export MHE types
export type {
  TelematicsRecord,
  TelematicsStatus,
  GeofenceZone,
  OperatorCertification,
  CertificationType,
  CertificationStatus,
  TrainingRecord,
  SafetyIncident,
  IncidentType,
  IncidentSeverity,
  IncidentStatus,
  PreShiftSafetyCheck,
  SafetyCheckItem,
  ChargingDock,
  ChargingDockStatus,
  ChargingSession,
  BatterySwap,
  MaintenanceWorkOrder,
  MaintenanceWorkOrderStatus,
  MaintenanceWorkOrderPriority,
  SparePart,
  EquipmentLifecycle,
  MHEStats,
} from '../types/mhe';
