// Customs & ICEGATE Exports
export {
  CustomsEngine,
  getCustomsEngine,
  setCustomsEngine,
  type CreateBOEInput,
  type BOEAssessmentInput,
  type DutyPaymentInput,
  type BOEQueryOptions,
  type CreateSBInput,
  type SBQueryOptions,
  type OrderExaminationInput,
  type CompleteExaminationInput,
  type ExaminationQueryOptions,
  type ProcessInboundMessageInput,
  type ICEGATEMessageQueryOptions,
  type CustomsStats,
} from './customs-engine';

// Re-export customs types
export type {
  BillOfEntry,
  BOEType,
  BOEStatus,
  BOEContainer,
  BOELineItem,
  BOEDocument,
  BOEDocumentType,
  ShippingBill,
  SBType,
  SBStatus,
  SBContainer,
  SBLineItem,
  SBDocument,
  SBDocumentType,
  CustomsExamination,
  ExaminationType,
  ExaminationResult,
  ExamDiscrepancy,
  ExamPhoto,
  ICEGATEMessage,
  ICEGATEMessageType,
  DutyChallan,
} from '../types/customs';
