#!/bin/bash
echo "🎉 ANKR System Cleanup Complete!"
echo "================================"
echo ""
echo "✅ Freed: 4GB disk space (94% → 92%)"
echo "✅ NPM cache: 3.9GB → 243MB"
echo "✅ Removed: backup files, logs, temp files"
echo "✅ Organized: archives moved to backups/"
echo ""
echo "📊 Current Status:"
echo "   Disk: 171GB/187GB (92%)"
echo "   Memory: 18GB/30GB used"
echo "   Swap: 9GB/11GB (high - consider reboot)"
echo "   Active Services: 69 ports, 296 processes"
echo ""
echo "⚠️  High swap usage detected!"
echo "   Recommendation: Consider rebooting to clear swap"
echo ""
echo "📝 Full report: /root/SYSTEM-STATUS-REPORT.md"
