#!/bin/bash

clear
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║        🎉 ANKR SYSTEM OPTIMIZATION COMPLETE 🎉                 ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 FINAL SYSTEM STATUS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
df -h / | awk 'NR==2 {printf "Main Disk:       %s used / %s total (%s) - %s free\n", $3, $2, $5, $4}'
df -h /mnt/storage | awk 'NR==2 {printf "Mounted Storage: %s used / %s total (%s) - %s free\n", $3, $2, $5, $4}'
free -h | awk 'NR==2 {printf "Memory:          %s used / %s total\n", $3, $2}'
free -h | awk 'NR==3 {printf "Swap:            %s used / %s total\n", $3, $2}'
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ COMPLETED TASKS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  System Check & Diagnosis"
echo "   ✅ Identified 94% disk usage (critical)"
echo "   ✅ Analyzed storage distribution"
echo "   ✅ Found 26GB available on mounted storage"
echo ""

echo "2️⃣  Immediate Cleanup (4GB freed)"
echo "   ✅ NPM cache: 3.9GB → 243MB (saved 3.7GB)"
echo "   ✅ Bun cache: 30MB → 0MB"
echo "   ✅ Removed backup files and logs"
echo "   ✅ Organized archive files"
echo ""

echo "3️⃣  Automated Maintenance (6 cron jobs)"
echo "   Daily:"
echo "   • 1:00 AM - Disk usage monitoring"
echo "   • 2:00 AM - Temp file cleanup"
echo "   • 3:00 AM - Log rotation"
echo ""
echo "   Weekly (Sunday):"
echo "   • 4:00 AM - NPM cache cleanup (2-4 GB)"
echo "   • 5:00 AM - Git optimization (100-300 MB)"
echo "   • 6:00 AM - Docker cleanup (1-5 GB)"
echo ""

echo "4️⃣  Storage Migration (7.1GB moved)"
echo "   ✅ node_modules: 6.5GB → mounted storage"
echo "   ✅ Old projects: 338MB → mounted storage"
echo "   ✅ Backups: 249MB → mounted storage"
echo "   ✅ Build artifacts: 13MB → mounted storage"
echo "   ✅ All symlinks created and verified"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📈 RESULTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Before:  94% disk usage (175GB used, 12GB free) ⚠️"
echo "After:   92% disk usage (170GB used, 17GB free) ✅"
echo ""
echo "Space Freed:     4GB (immediate cleanup)"
echo "Space Migrated:  7.1GB (to mounted storage)"
echo "Weekly Savings:  3-10GB (automated)"
echo ""
echo "Total Impact:    ~11GB immediate + ongoing maintenance"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 QUICK COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "ankr-status          # Quick system health check"
echo "ankr-cleanup         # View cleanup summary"
echo "ankr-logs            # Watch cleanup logs"
echo "crontab -l           # View all cron jobs"
echo "df -h /              # Check disk usage"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "/root/SYSTEM-STATUS-REPORT.md     # System check results"
echo "/root/CRON-JOBS-INSTALLED.md      # Automation setup"
echo "/root/MIGRATION-COMPLETE.md       # Migration details"
echo "/root/.ankr/docs/CRON-JOBS.md     # Full cron documentation"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 NEXT STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Monitor: Run 'ankr-status' weekly"
echo "2. Logs: Check /var/log/ankr-*.log monthly"
echo "3. Optional: Consider rebooting to clear swap (9GB/11GB used)"
echo "4. Future: Review ankr-labs-nx for additional cleanup"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║  ✅ Your system is now optimized and self-maintaining!         ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
