#!/bin/bash

echo "════════════════════════════════════════════════════════════════════════"
echo "  🚀 MARI8X GITHUB AUTO-DEPLOY - PERMANENT SOLUTION"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Code pushed to GitHub (commit: 0d43acc)"
echo "✅ Frontend build ready"
echo "✅ Backend live at mari8x.com/health"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📋 FOLLOW THESE 5 STEPS IN CLOUDFLARE DASHBOARD"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  OPEN CLOUDFLARE PAGES"
echo "    👉 https://dash.cloudflare.com/1c452912df3eea9e8f1a2a973ff337f5/pages"
echo ""
echo "2️⃣  CLICK 'Create a project' → 'Connect to Git' → 'GitHub'"
echo ""
echo "3️⃣  SELECT REPOSITORY: rocketlang/dodd-icd"
echo ""
echo "4️⃣  CONFIGURE BUILD (copy these exactly):"
echo ""
echo "    Project name:          mari8x"
echo "    Production branch:     master"
echo "    Root directory:        /"
echo ""
echo "    Build command:"
echo "    cd apps/ankr-maritime/frontend && npm install && npx vite build"
echo ""
echo "    Build output directory:"
echo "    apps/ankr-maritime/frontend/dist"
echo ""
echo "5️⃣  CLICK 'Save and Deploy'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⏱️  AFTER FIRST DEPLOYMENT (2-3 minutes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "6️⃣  ADD CUSTOM DOMAIN"
echo "    • Go to project settings → Custom domains"
echo "    • Add: mari8x.com"
echo "    • Cloudflare auto-configures DNS"
echo "    • SSL provisions automatically"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "  🎉 RESULT: PERMANENT AUTO-DEPLOYMENT"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Future deployments:"
echo "  git push  →  Cloudflare automatically builds & deploys  →  Live in 3 min"
echo ""
echo "No more manual uploads!"
echo "No more file transfers!"
echo "No more natak!"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "📖 Full guide: /root/CLOUDFLARE-PAGES-SETUP.md"
echo ""
