#!/bin/bash

clear
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "  ✅ AUTOMATION COMPLETE - ONE STEP LEFT"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "🤖 GitHub Actions workflow is live and ready!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📋 DO THIS NOW (30 seconds):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open this URL:"
echo ""
echo "   👉 https://github.com/rocketlang/dodd-icd/settings/secrets/actions/new"
echo ""
echo "2. Fill in:"
echo ""
echo "   Name:  CLOUDFLARE_API_TOKEN"
echo "   Value: [paste your Cloudflare API token]"
echo ""
echo "3. Click 'Add secret'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🚀 THEN DEPLOY:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option A - Trigger manually:"
echo "  👉 https://github.com/rocketlang/dodd-icd/actions"
echo "  Click: 'Deploy Mari8X to Cloudflare Pages' → 'Run workflow'"
echo ""
echo "Option B - Push any change:"
echo "  git commit --allow-empty -m 'feat: Deploy Mari8X'"
echo "  git push"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "  🎉 FOREVER AFTER:"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "  git push  →  Automatic build & deploy  →  Live on mari8x.com"
echo ""
echo "  No manual work. No file transfers. No natak."
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""

chmod +x /root/NEXT-STEP.sh
