/**
 * Subscription topic constants — used by event bridge and resolvers
 */

export const SUBSCRIPTION_TOPICS = {
  CONTAINER_STATUS_CHANGED: 'CONTAINER_STATUS_CHANGED',
  CONTAINER_MOVED: 'CONTAINER_MOVED',
  GATE_TRANSACTION_UPDATED: 'GATE_TRANSACTION_UPDATED',
  RAKE_STATUS_CHANGED: 'RAKE_STATUS_CHANGED',
  VESSEL_STATUS_CHANGED: 'VESSEL_STATUS_CHANGED',
  EQUIPMENT_ALERT: 'EQUIPMENT_ALERT',
  YARD_CAPACITY_ALERT: 'YARD_CAPACITY_ALERT',
  REEFER_ALARM: 'REEFER_ALARM',
  SENSOR_ALERT: 'SENSOR_ALERT',
  OPERATION_COMPLETED: 'OPERATION_COMPLETED',
  DOCUMENT_ISSUED: 'DOCUMENT_ISSUED',
} as const;

export type SubscriptionTopic = typeof SUBSCRIPTION_TOPICS[keyof typeof SUBSCRIPTION_TOPICS];
